Src/Presentation/WebApp/Controllers/DynamicObjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nexawo.Application.DynamicObjects;
using Nexawo.Application.DynamicObjects.Commands.CreateController;
using Nexawo.Application.DynamicObjects.Commands.CreateModel;
using Nexawo.Application.DynamicObjects.Commands.CreateView;
using Nexawo.Application.DynamicObjects.Queries.GetFieldsList;

namespace Nexawo.WebApp.Controllers
{
    public class DynamicObjectsController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> Create([FromBody]DynamicObjectDTO dynamicObjectDTO)
        {            
            var command = new CreateModelCommand();
            command.DynamicObjectDTO = dynamicObjectDTO;
            bool result = await Mediator.Send(command);
            if (result)
            {
                var controllerCommand = new CreateControllerCommand();
                controllerCommand.DynamicObjectDTO = dynamicObjectDTO;
                result = await Mediator.Send(controllerCommand);
                if (result)
                {
                    var viewCommand = new CreateViewCommand();
                    viewCommand.DynamicObjectDTO = dynamicObjectDTO;
                    result = await Mediator.Send(viewCommand);
                }
            }
            return Json(dynamicObjectDTO);
        }
        
        [HttpPost]
        public async Task<JsonResult> GetServiceDetailByPage(string service, string page)
        {
            
            var result = await Mediator.Send(new GetFieldsListQuery {Page = page,Service = service });
           // var result = new List<FieldsDetailViewModel>();
           // using (var dbContext = new HMSContextNexawo())
           // {
           //     var response = dbContext.ServiceDetails.Where(row => row.Service == service && row.Page == page).FirstOrDefault();
           //     if (response != null)
           //     {
           //         result = JsonConvert.DeserializeObject<List<FieldsDetailViewModel>>(response.Content);
           //     }
           //
           //
           // }
            return Json(result.Fields);
        }
    }
}

Src/Presentation/WebApp/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nexawo.Application.Employee.Commands.Create_Employee;
using Nexawo.Application.Employees.Commands;
using Nexawo.Application.Employees.Commands.DeleteEmployee;
using Nexawo.Application.Employees.Commands.UpdateEmployee;
using Nexawo.Application.Employees.Queries.GetEmployeeDetail;
using Nexawo.Application.Employees.Queries.GetEmployeeList;

namespace Nexawo.WebApp.Controllers
{
    public class EmployeeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> List()
        {
            var list = await Mediator.Send(new GetEmployeeListQuery());
            
            return View(list.Employees);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(EmployeeDTO serviceDTO)
        {
            var createServiceCommand = new CreateEmployeeCommand();
          //  serviceDTO.EmployeeId = 1;
            createServiceCommand.EmployeeDTO = serviceDTO; 
            int result = await Mediator.Send(createServiceCommand);
            return RedirectToAction("List");
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Edit(int id)
        {
            var employee = await Mediator.Send(new GetEmployeeDetailQuery { EmployeeID = id });
            return View(employee);
        }
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Edit(EmployeeDetailVM employeeDetailVM)
        {
            var updateEmployeeCommand = new UpdateEmployeeCommand()
            {
                EmployeeId = employeeDetailVM.EmployeeId,
                FirstName = employeeDetailVM.FirstName,
                LastName = employeeDetailVM.LastName,
                CNIC = employeeDetailVM.CNIC,
                Email = employeeDetailVM.Email,
                Age = employeeDetailVM.Age,
                Address = employeeDetailVM.Address
            };
            //var updateTenantCommand = _mapper.Map<UpdateTenantCommand>(tenantDetailVM);
            var employee = await Mediator.Send(updateEmployeeCommand);
            return RedirectToAction("List");
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Delete(int id)
        {
            var employee = await Mediator.Send(new GetEmployeeDetailQuery { EmployeeID = id });
            return View(employee);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Delete(int id, string confirm = null)
        {
            var deleteEmployeeCommand = new DeleteEmployeeCommand()
            {
                EmployeeId = id
            };
            var result = await Mediator.Send(deleteEmployeeCommand);
            return RedirectToAction("List");
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Detail(int id)
        {
            var employee = await Mediator.Send(new GetEmployeeDetailQuery { EmployeeID = id });
            return View(employee);
        }
    }
}

Src/Presentation/WebApp/Controllers/TenantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nexawo.Application.Tenants.Commands.CreateTenant;
using Nexawo.Application.Tenants.Commands.DeleteTenant;
using Nexawo.Application.Tenants.Commands.UpdateTenant;
using Nexawo.Application.Tenants.Queries.GetTenantDetail;
using Nexawo.Application.Tenants.Queries.GetTenantsList;
using Nexawo.Application.Users.Queries.GetUsersListByTenant;

namespace Nexawo.WebApp.Controllers
{
    public class TenantController : BaseController
    {
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> List()
        {            
            var list = await Mediator.Send(new GetTenantsListQuery());
           
            return View(list.Tenants);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Add(CreateTenantCommand command)
        {
            command.TenantId = Guid.NewGuid().ToString();
            await Mediator.Send(command);
            return RedirectToAction("List");
        }
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Edit(string id)
        {
            var tenant = await Mediator.Send(new GetTenantDetailQuery { Id = id });
            return View(tenant);
        }
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Edit(TenantDetailVM tenantDetailVM)
        { 
            var updateTenantCommand = new UpdateTenantCommand() 
            {
                TenantId = tenantDetailVM.TenantId,
                Name = tenantDetailVM.Name,
                DBConnection = tenantDetailVM.DBConnection
            };
            //var updateTenantCommand = _mapper.Map<UpdateTenantCommand>(tenantDetailVM);
            var tenant = await Mediator.Send(updateTenantCommand);
            return RedirectToAction("List");
        }
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Detail(string id)
        {
            var tenant = await Mediator.Send(new GetTenantDetailQuery { Id = id });
            var tenantUsers = await Mediator.Send(new GetUsersListByTenantQuery { TenantId = id });
            ViewBag.TenantUsers = tenantUsers.Users;
            return View(tenant);
        }
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Delete(string id)
        {
            var tenant = await Mediator.Send(new GetTenantDetailQuery { Id = id });
            return View(tenant);
        }
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Delete(string id,string confirm = null)
        {
            var deleteTenantCommand = new DeleteTenantCommand()
            {
                Id = id
            };
            var result = await Mediator.Send(deleteTenantCommand);
            return RedirectToAction("List");
        }
    }
}

Src/Presentation/WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nexawo.Application.Users.Commands;
using Nexawo.Application.Users.Queries.GetUsersList;
using Nexawo.Application.Users.Queries.GetUsersListByTenant;
using Nexawo.Application.Users.Queries.UserLogin;
using Nexawo.WebApp.Controllers;

namespace WebApp.Controllers
{
    public class UserController : BaseController
    {
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserDTO userDTO)
        {

            var user = await Mediator.Send(new UserLoginQuery { Email = userDTO.Email, Password = userDTO.Password });
            if (user == null)
                return View();
            else
            {
                HttpContext.Session.SetString("Service", "Service1");
                return RedirectToAction("Index", "Home");
            }
            
        }
        public async Task<IActionResult> List()
        {
            var usersList = await Mediator.Send(new GetUsersListQuery());
            return View(usersList.Users);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(UserDTO userDTO)
        {
            var createUserCommand = new CreateUserCommand();
            createUserCommand.UserDTO = userDTO;
            int result = await Mediator.Send(createUserCommand);
            return RedirectToAction("List");
        }
    }
}

Src/Presentation/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nexawo - Hospital Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />    
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nexawo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="List">Service</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tenant" asp-action="List">Tenant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DynamicObjects" asp-action="Index">Objects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="List">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>